import { Story } from '../types';

const now = new Date();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60_000).toISOString();

export const MOCK_STORIES: Story[] = [
  {
    id: 'mock-story-1',
    headline: 'OpenAI Announces GPT-5 With Reasoning Breakthrough',
    summary:
      'OpenAI has unveiled GPT-5, claiming significant improvements in multi-step reasoning and real-time knowledge retrieval. The model is expected to roll out to ChatGPT Plus users starting next week.',
    representativeTweets: [
      {
        id: 'mock-tweet-1a',
        text: 'BREAKING: OpenAI just announced GPT-5. Sam Altman says it represents a "qualitative leap" in reasoning capabilities. Early benchmarks look insane.',
        authorUsername: 'elonmusk',
        authorDisplayName: 'Elon Musk',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1845482317835034624/5JInT3ag_400x400.jpg',
        createdAt: minutesAgo(12),
        likeCount: 84200,
        retweetCount: 22300,
        replyCount: 5100,
      },
      {
        id: 'mock-tweet-1b',
        text: 'GPT-5 just passed the bar exam with a 98th percentile score, up from 90th for GPT-4. The reasoning chain improvements are real.',
        authorUsername: 'sama',
        authorDisplayName: 'Sam Altman',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/804990434455887872/BG0Xh7Oa_400x400.jpg',
        createdAt: minutesAgo(25),
        likeCount: 42100,
        retweetCount: 9800,
        replyCount: 3200,
      },
      {
        id: 'mock-tweet-1c',
        text: 'I\'ve been testing GPT-5 for the past week. The ability to hold complex context across long conversations is a game changer for coding.',
        authorUsername: 'karpathy',
        authorDisplayName: 'Andrej Karpathy',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1296667294148382721/9Pr6XrPB_400x400.jpg',
        createdAt: minutesAgo(18),
        likeCount: 31500,
        retweetCount: 6700,
        replyCount: 1900,
      },
    ],
    isHeadline: true,
    score: 98.5,
    totalEngagement: 205800,
    velocity: 42.3,
    uniqueAuthors: 3,
    clusterSize: 47,
    generatedAt: minutesAgo(5),
  },
  {
    id: 'mock-story-2',
    headline: 'EU Passes Landmark AI Regulation Framework',
    summary:
      'The European Parliament has approved comprehensive AI legislation requiring transparency disclosures for foundation models and banning certain surveillance applications. Tech companies have 18 months to comply.',
    representativeTweets: [
      {
        id: 'mock-tweet-2a',
        text: 'JUST IN: EU Parliament passes the AI Act with a strong majority. Foundation model providers must now disclose training data sources and energy consumption.',
        authorUsername: 'Reuters',
        authorDisplayName: 'Reuters',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1194751949821939712/3VBbMchL_400x400.jpg',
        createdAt: minutesAgo(45),
        likeCount: 12400,
        retweetCount: 8900,
        replyCount: 2100,
      },
      {
        id: 'mock-tweet-2b',
        text: 'The EU AI Act is a watershed moment. Companies building AI will need to fundamentally rethink transparency. This will shape global norms.',
        authorUsername: 'ylecun',
        authorDisplayName: 'Yann LeCun',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1483577865056702469/rWA-3_T7_400x400.jpg',
        createdAt: minutesAgo(30),
        likeCount: 8200,
        retweetCount: 3100,
        replyCount: 890,
      },
    ],
    isHeadline: false,
    score: 82.1,
    totalEngagement: 35590,
    velocity: 28.7,
    uniqueAuthors: 2,
    clusterSize: 31,
    generatedAt: minutesAgo(10),
  },
  {
    id: 'mock-story-3',
    headline: 'SpaceX Starship Completes First Orbital Refueling Test',
    summary:
      'SpaceX successfully demonstrated in-orbit propellant transfer between two Starship vehicles, a critical milestone for NASA\'s Artemis moon landing program. The test lasted approximately 30 minutes.',
    representativeTweets: [
      {
        id: 'mock-tweet-3a',
        text: 'Starship orbital refueling test is COMPLETE. Both vehicles performed nominally. This unlocks deep space missions. Mars is getting closer.',
        authorUsername: 'SpaceX',
        authorDisplayName: 'SpaceX',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1082744382585856001/rH_k3PtQ_400x400.jpg',
        createdAt: minutesAgo(60),
        likeCount: 95000,
        retweetCount: 28400,
        replyCount: 6200,
      },
      {
        id: 'mock-tweet-3b',
        text: 'Congratulations @SpaceX on the successful orbital refueling demo! This is a key step toward sustainable lunar exploration under Artemis.',
        authorUsername: 'NASA',
        authorDisplayName: 'NASA',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/188302352/nasalogo_twitter_400x400.jpg',
        createdAt: minutesAgo(50),
        likeCount: 44000,
        retweetCount: 11200,
        replyCount: 3100,
      },
    ],
    isHeadline: false,
    score: 91.3,
    totalEngagement: 188000,
    velocity: 35.8,
    uniqueAuthors: 2,
    clusterSize: 52,
    generatedAt: minutesAgo(8),
  },
  {
    id: 'mock-story-4',
    headline: 'Bitcoin Surges Past $150K on ETF Inflows',
    summary:
      'Bitcoin has broken through the $150,000 mark for the first time, driven by record inflows into spot Bitcoin ETFs. BlackRock\'s IBIT alone saw $2.1B in single-day volume.',
    representativeTweets: [
      {
        id: 'mock-tweet-4a',
        text: '$BTC just broke $150K. Spot ETF inflows are absolutely monstrous right now — BlackRock IBIT did $2.1B in volume today alone. Institutional adoption is here.',
        authorUsername: 'APompliano',
        authorDisplayName: 'Anthony Pompliano',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1587824553498763265/MlTFUHwK_400x400.jpg',
        createdAt: minutesAgo(15),
        likeCount: 18900,
        retweetCount: 5600,
        replyCount: 2300,
      },
      {
        id: 'mock-tweet-4b',
        text: 'Bitcoin at $150K. I remember when people laughed at the $100K prediction. The supply shock from the halving + ETF demand is playing out exactly as modeled.',
        authorUsername: 'michael_saylor',
        authorDisplayName: 'Michael Saylor',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1430639043184603139/i53FDVdH_400x400.jpg',
        createdAt: minutesAgo(20),
        likeCount: 25100,
        retweetCount: 7200,
        replyCount: 1800,
      },
    ],
    isHeadline: false,
    score: 76.4,
    totalEngagement: 60900,
    velocity: 31.2,
    uniqueAuthors: 2,
    clusterSize: 38,
    generatedAt: minutesAgo(3),
  },
  {
    id: 'mock-story-5',
    headline: 'Apple Reveals Vision Pro 2 With Major Weight Reduction',
    summary:
      'Apple announced the second generation Vision Pro at a special event, featuring a 40% weight reduction and a new M5 chip. The device will ship at $2,999, $500 less than the original.',
    representativeTweets: [
      {
        id: 'mock-tweet-5a',
        text: 'Vision Pro 2 is here: 40% lighter, M5 chip, improved passthrough, and $2,999 starting price. This is the version that could actually go mainstream.',
        authorUsername: 'markgurman',
        authorDisplayName: 'Mark Gurman',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1622296835356white160000/ZkGOGOCj_400x400.jpg',
        createdAt: minutesAgo(90),
        likeCount: 15600,
        retweetCount: 4200,
        replyCount: 1400,
      },
      {
        id: 'mock-tweet-5b',
        text: 'Just tried Vision Pro 2. The weight difference is immediately noticeable — you almost forget you\'re wearing it after 10 minutes. Night and day vs V1.',
        authorUsername: 'MKBHD',
        authorDisplayName: 'Marques Brownlee',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1468001914302390278/B_Xv_8gu_400x400.jpg',
        createdAt: minutesAgo(75),
        likeCount: 52000,
        retweetCount: 8900,
        replyCount: 3200,
      },
    ],
    isHeadline: false,
    score: 72.8,
    totalEngagement: 85300,
    velocity: 22.1,
    uniqueAuthors: 2,
    clusterSize: 29,
    generatedAt: minutesAgo(15),
  },
  {
    id: 'mock-story-6',
    headline: 'Google DeepMind Solves New Class of Math Problems',
    summary:
      'Google DeepMind\'s AlphaProof system has solved several previously unproven mathematical conjectures, marking the first time an AI system has produced novel, peer-verified mathematical proofs at this level.',
    representativeTweets: [
      {
        id: 'mock-tweet-6a',
        text: 'AlphaProof just produced novel proofs for 3 open conjectures in combinatorics. These have been verified by peer review. We\'re entering a new era of AI-assisted mathematics.',
        authorUsername: 'demaborsa',
        authorDisplayName: 'Demis Hassabis',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1799438523654443008/FqDGXIC__400x400.jpg',
        createdAt: minutesAgo(120),
        likeCount: 28400,
        retweetCount: 9100,
        replyCount: 2400,
      },
      {
        id: 'mock-tweet-6b',
        text: 'This is genuinely remarkable. AlphaProof isn\'t just verifying known results — it\'s discovering new mathematics. The implications for research are profound.',
        authorUsername: 'TerryTaoMaths',
        authorDisplayName: 'Terence Tao',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1414304708095045634/RA6KVxyF_400x400.jpg',
        createdAt: minutesAgo(100),
        likeCount: 19800,
        retweetCount: 5600,
        replyCount: 1200,
      },
    ],
    isHeadline: false,
    score: 69.2,
    totalEngagement: 66500,
    velocity: 18.4,
    uniqueAuthors: 2,
    clusterSize: 24,
    generatedAt: minutesAgo(20),
  },
];
