import { Story } from '../types';

const now = new Date();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60_000).toISOString();

export const MOCK_STORIES: Story[] = [
  {
    id: 'mock-story-1',
    headline: 'OpenAI Announces GPT-5 With Reasoning Breakthrough',
    summary:
      'OpenAI has unveiled GPT-5, claiming significant improvements in multi-step reasoning and real-time knowledge retrieval. The model is expected to roll out to ChatGPT Plus users starting next week.',
    representativeTweets: [
      {
        id: 'mock-tweet-1a',
        text: 'BREAKING: OpenAI just announced GPT-5. Sam Altman says it represents a "qualitative leap" in reasoning capabilities. Early benchmarks look insane.',
        authorUsername: 'elonmusk',
        authorDisplayName: 'Elon Musk',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1845482317835034624/5JInT3ag_400x400.jpg',
        createdAt: minutesAgo(12),
        likeCount: 84200,
        retweetCount: 22300,
        replyCount: 5100,
      },
      {
        id: 'mock-tweet-1b',
        text: 'GPT-5 just passed the bar exam with a 98th percentile score, up from 90th for GPT-4. The reasoning chain improvements are real.',
        authorUsername: 'sama',
        authorDisplayName: 'Sam Altman',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/804990434455887872/BG0Xh7Oa_400x400.jpg',
        createdAt: minutesAgo(25),
        likeCount: 42100,
        retweetCount: 9800,
        replyCount: 3200,
      },
      {
        id: 'mock-tweet-1c',
        text: 'I\'ve been testing GPT-5 for the past week. The ability to hold complex context across long conversations is a game changer for coding.',
        authorUsername: 'karpathy',
        authorDisplayName: 'Andrej Karpathy',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1296667294148382721/9Pr6XrPB_400x400.jpg',
        createdAt: minutesAgo(18),
        likeCount: 31500,
        retweetCount: 6700,
        replyCount: 1900,
      },
    ],
    isHeadline: true,
    category: 'ai',
    score: 0.98,
    totalEngagement: 205800,
    velocity: 12450,
    uniqueAuthors: 3,
    clusterSize: 47,
    totalImpressions: 15200000,
    generatedAt: minutesAgo(5),
  },
  {
    id: 'mock-story-2',
    headline: 'EU Passes Landmark AI Regulation Framework',
    summary:
      'The European Parliament has approved comprehensive AI legislation requiring transparency disclosures for foundation models and banning certain surveillance applications. Tech companies have 18 months to comply.',
    representativeTweets: [
      {
        id: 'mock-tweet-2a',
        text: 'JUST IN: EU Parliament passes the AI Act with a strong majority. Foundation model providers must now disclose training data sources and energy consumption.',
        authorUsername: 'Reuters',
        authorDisplayName: 'Reuters',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1194751949821939712/3VBbMchL_400x400.jpg',
        createdAt: minutesAgo(45),
        likeCount: 12400,
        retweetCount: 8900,
        replyCount: 2100,
      },
      {
        id: 'mock-tweet-2b',
        text: 'The EU AI Act is a watershed moment. Companies building AI will need to fundamentally rethink transparency. This will shape global norms.',
        authorUsername: 'ylecun',
        authorDisplayName: 'Yann LeCun',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1483577865056702469/rWA-3_T7_400x400.jpg',
        createdAt: minutesAgo(30),
        likeCount: 8200,
        retweetCount: 3100,
        replyCount: 890,
      },
    ],
    isHeadline: false,
    category: 'ai',
    score: 0.82,
    totalEngagement: 35590,
    velocity: 3420,
    uniqueAuthors: 2,
    clusterSize: 31,
    totalImpressions: 8500000,
    generatedAt: minutesAgo(10),
  },
  {
    id: 'mock-story-3',
    headline: 'SpaceX Starship Completes First Orbital Refueling Test',
    summary:
      'SpaceX successfully demonstrated in-orbit propellant transfer between two Starship vehicles, a critical milestone for NASA\'s Artemis moon landing program. The test lasted approximately 30 minutes.',
    representativeTweets: [
      {
        id: 'mock-tweet-3a',
        text: 'Starship orbital refueling test is COMPLETE. Both vehicles performed nominally. This unlocks deep space missions. Mars is getting closer.',
        authorUsername: 'SpaceX',
        authorDisplayName: 'SpaceX',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1082744382585856001/rH_k3PtQ_400x400.jpg',
        createdAt: minutesAgo(60),
        likeCount: 95000,
        retweetCount: 28400,
        replyCount: 6200,
      },
      {
        id: 'mock-tweet-3b',
        text: 'Congratulations @SpaceX on the successful orbital refueling demo! This is a key step toward sustainable lunar exploration under Artemis.',
        authorUsername: 'NASA',
        authorDisplayName: 'NASA',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/188302352/nasalogo_twitter_400x400.jpg',
        createdAt: minutesAgo(50),
        likeCount: 44000,
        retweetCount: 11200,
        replyCount: 3100,
      },
    ],
    isHeadline: false,
    category: 'technology',
    score: 0.91,
    totalEngagement: 188000,
    velocity: 8920,
    uniqueAuthors: 2,
    clusterSize: 52,
    totalImpressions: 22000000,
    generatedAt: minutesAgo(8),
  },
  {
    id: 'mock-story-4',
    headline: 'Bitcoin Surges Past $150K on ETF Inflows',
    summary:
      'Bitcoin has broken through the $150,000 mark for the first time, driven by record inflows into spot Bitcoin ETFs. BlackRock\'s IBIT alone saw $2.1B in single-day volume.',
    representativeTweets: [
      {
        id: 'mock-tweet-4a',
        text: '$BTC just broke $150K. Spot ETF inflows are absolutely monstrous right now — BlackRock IBIT did $2.1B in volume today alone. Institutional adoption is here.',
        authorUsername: 'APompliano',
        authorDisplayName: 'Anthony Pompliano',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1587824553498763265/MlTFUHwK_400x400.jpg',
        createdAt: minutesAgo(15),
        likeCount: 18900,
        retweetCount: 5600,
        replyCount: 2300,
      },
      {
        id: 'mock-tweet-4b',
        text: 'Bitcoin at $150K. I remember when people laughed at the $100K prediction. The supply shock from the halving + ETF demand is playing out exactly as modeled.',
        authorUsername: 'michael_saylor',
        authorDisplayName: 'Michael Saylor',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1430639043184603139/i53FDVdH_400x400.jpg',
        createdAt: minutesAgo(20),
        likeCount: 25100,
        retweetCount: 7200,
        replyCount: 1800,
      },
    ],
    isHeadline: false,
    category: 'business',
    score: 0.76,
    totalEngagement: 60900,
    velocity: 6850,
    uniqueAuthors: 2,
    clusterSize: 38,
    totalImpressions: 4200000,
    generatedAt: minutesAgo(3),
  },
  {
    id: 'mock-story-5',
    headline: 'Apple Reveals Vision Pro 2 With Major Weight Reduction',
    summary:
      'Apple announced the second generation Vision Pro at a special event, featuring a 40% weight reduction and a new M5 chip. The device will ship at $2,999, $500 less than the original.',
    representativeTweets: [
      {
        id: 'mock-tweet-5a',
        text: 'Vision Pro 2 is here: 40% lighter, M5 chip, improved passthrough, and $2,999 starting price. This is the version that could actually go mainstream.',
        authorUsername: 'markgurman',
        authorDisplayName: 'Mark Gurman',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1622296835356white160000/ZkGOGOCj_400x400.jpg',
        createdAt: minutesAgo(90),
        likeCount: 15600,
        retweetCount: 4200,
        replyCount: 1400,
      },
      {
        id: 'mock-tweet-5b',
        text: 'Just tried Vision Pro 2. The weight difference is immediately noticeable — you almost forget you\'re wearing it after 10 minutes. Night and day vs V1.',
        authorUsername: 'MKBHD',
        authorDisplayName: 'Marques Brownlee',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1468001914302390278/B_Xv_8gu_400x400.jpg',
        createdAt: minutesAgo(75),
        likeCount: 52000,
        retweetCount: 8900,
        replyCount: 3200,
      },
    ],
    isHeadline: false,
    category: 'technology',
    score: 0.73,
    totalEngagement: 85300,
    velocity: 2210,
    uniqueAuthors: 2,
    clusterSize: 29,
    totalImpressions: 3100000,
    generatedAt: minutesAgo(15),
  },
  {
    id: 'mock-story-6',
    headline: 'Google DeepMind Solves New Class of Math Problems',
    summary:
      'Google DeepMind\'s AlphaProof system has solved several previously unproven mathematical conjectures, marking the first time an AI system has produced novel, peer-verified mathematical proofs at this level.',
    representativeTweets: [
      {
        id: 'mock-tweet-6a',
        text: 'AlphaProof just produced novel proofs for 3 open conjectures in combinatorics. These have been verified by peer review. We\'re entering a new era of AI-assisted mathematics.',
        authorUsername: 'demaborsa',
        authorDisplayName: 'Demis Hassabis',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1799438523654443008/FqDGXIC__400x400.jpg',
        createdAt: minutesAgo(120),
        likeCount: 28400,
        retweetCount: 9100,
        replyCount: 2400,
      },
      {
        id: 'mock-tweet-6b',
        text: 'This is genuinely remarkable. AlphaProof isn\'t just verifying known results — it\'s discovering new mathematics. The implications for research are profound.',
        authorUsername: 'TerryTaoMaths',
        authorDisplayName: 'Terence Tao',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/1414304708095045634/RA6KVxyF_400x400.jpg',
        createdAt: minutesAgo(100),
        likeCount: 19800,
        retweetCount: 5600,
        replyCount: 1200,
      },
    ],
    isHeadline: false,
    category: 'ai',
    score: 0.69,
    totalEngagement: 66500,
    velocity: 1840,
    uniqueAuthors: 2,
    clusterSize: 24,
    totalImpressions: 2800000,
    generatedAt: minutesAgo(20),
  },
  {
    id: 'mock-story-7',
    headline: 'Nvidia Unveils Blackwell Ultra GPUs With 2x Training Performance',
    summary:
      'Nvidia announced the Blackwell Ultra B300 GPU at GTC, claiming double the AI training throughput over the previous Hopper generation. Major cloud providers have already committed to deploying the chips in Q3.',
    representativeTweets: [
      {
        id: 'mock-tweet-7a',
        text: 'Nvidia Blackwell Ultra B300 is a monster. 2x training performance over H100, 4x inference throughput. Jensen just casually announced the next era of compute.',
        authorUsername: 'juaborsa',
        authorDisplayName: 'Juan Benet',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(25),
        likeCount: 14200,
        retweetCount: 3800,
        replyCount: 920,
      },
      {
        id: 'mock-tweet-7b',
        text: 'NVDA up 8% pre-market on B300 announcement. AWS, Azure, and GCP all confirmed day-one deployment. The GPU shortage is about to get worse before it gets better.',
        authorUsername: 'DeItaone',
        authorDisplayName: 'Walter Bloomberg',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(28),
        likeCount: 9300,
        retweetCount: 2900,
        replyCount: 710,
      },
      {
        id: 'mock-tweet-7c',
        text: 'The B300 memory bandwidth numbers are wild — 12 TB/s on HBM4. This changes the calculus on what model sizes you can train efficiently in a single node.',
        authorUsername: 'chipanalyst',
        authorDisplayName: 'Dylan Patel',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(32),
        likeCount: 7100,
        retweetCount: 1600,
        replyCount: 430,
      },
    ],
    isHeadline: false,
    category: 'ai',
    score: 0.75,
    totalEngagement: 40960,
    velocity: 3820,
    uniqueAuthors: 3,
    clusterSize: 35,
    totalImpressions: 5600000,
    generatedAt: minutesAgo(22),
  },
  {
    id: 'mock-story-8',
    headline: 'Meta Releases Llama 4 as Fully Open-Source Model',
    summary:
      'Meta has released Llama 4, its largest open-source language model at 405B parameters, with full weights and training code. The model matches GPT-4 Turbo on most benchmarks and is free for commercial use.',
    representativeTweets: [
      {
        id: 'mock-tweet-8a',
        text: 'Llama 4 is out. 405B parameters, fully open weights, Apache 2.0 license. Benchmarks are neck-and-neck with GPT-4 Turbo. Open source AI just leveled up massively.',
        authorUsername: 'AIatMeta',
        authorDisplayName: 'Meta AI',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(40),
        likeCount: 22500,
        retweetCount: 8400,
        replyCount: 1900,
      },
      {
        id: 'mock-tweet-8b',
        text: 'Just ran Llama 4 locally on a 4x A100 setup. The quality is genuinely indistinguishable from the commercial APIs for most tasks. This changes the economics of AI deployment.',
        authorUsername: 'itsandrewgao',
        authorDisplayName: 'Andrew Gao',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(35),
        likeCount: 8700,
        retweetCount: 2100,
        replyCount: 640,
      },
    ],
    isHeadline: false,
    category: 'ai',
    score: 0.71,
    totalEngagement: 44240,
    velocity: 2940,
    uniqueAuthors: 2,
    clusterSize: 32,
    totalImpressions: 4800000,
    generatedAt: minutesAgo(30),
  },
  {
    id: 'mock-story-9',
    headline: 'Anthropic Claude 4 Tops Arena Leaderboard With Agentic Coding Skills',
    summary:
      'Anthropic released Claude 4, which immediately took the #1 spot on the Chatbot Arena leaderboard. The model shows particular strength in multi-step agentic coding tasks, outperforming competitors by a wide margin.',
    representativeTweets: [
      {
        id: 'mock-tweet-9a',
        text: 'Claude 4 is live and it\'s #1 on Arena. The agentic coding benchmarks are not even close — 92% on SWE-bench full vs 67% for the next best. Anthropic cooked.',
        authorUsername: 'DarioAmodei',
        authorDisplayName: 'Dario Amodei',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(55),
        likeCount: 18300,
        retweetCount: 6200,
        replyCount: 1500,
      },
      {
        id: 'mock-tweet-9b',
        text: 'I switched my entire dev workflow to Claude 4 this morning. It just refactored a 2000-line module autonomously, ran tests, and fixed its own bugs. This is different.',
        authorUsername: 'swaborsa',
        authorDisplayName: 'Swyx',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(48),
        likeCount: 11200,
        retweetCount: 3400,
        replyCount: 890,
      },
      {
        id: 'mock-tweet-9c',
        text: 'Claude 4\'s safety evals are also impressive. It refused 98% of jailbreak attempts while being significantly more helpful on legitimate queries. Constitutional AI paying off.',
        authorUsername: 'jackclarkSF',
        authorDisplayName: 'Jack Clark',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(42),
        likeCount: 6800,
        retweetCount: 1900,
        replyCount: 520,
      },
    ],
    isHeadline: false,
    category: 'ai',
    score: 0.73,
    totalEngagement: 50710,
    velocity: 3370,
    uniqueAuthors: 3,
    clusterSize: 38,
    totalImpressions: 4200000,
    generatedAt: minutesAgo(35),
  },
  {
    id: 'mock-story-10',
    headline: 'US and China Reach Surprise Agreement on Taiwan Strait Navigation',
    summary:
      'After months of escalating tensions, the US and China announced a joint framework for military-to-military communication in the Taiwan Strait. The deal includes a mutual commitment to avoid provocative naval maneuvers.',
    representativeTweets: [
      {
        id: 'mock-tweet-10a',
        text: 'BREAKING: US and China sign framework agreement on Taiwan Strait navigation protocols. Both sides commit to 48-hour advance notice for military transits. Huge de-escalation.',
        authorUsername: 'AP',
        authorDisplayName: 'The Associated Press',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(70),
        likeCount: 18600,
        retweetCount: 12400,
        replyCount: 3800,
      },
      {
        id: 'mock-tweet-10b',
        text: 'The Taiwan Strait agreement is more significant than it looks on paper. It establishes a direct military hotline that hasn\'t existed since 2022. Markets responding positively.',
        authorUsername: 'IanBremmer',
        authorDisplayName: 'Ian Bremmer',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(65),
        likeCount: 9400,
        retweetCount: 3800,
        replyCount: 1100,
      },
    ],
    isHeadline: false,
    category: 'politics',
    score: 0.69,
    totalEngagement: 49100,
    velocity: 2480,
    uniqueAuthors: 2,
    clusterSize: 28,
    totalImpressions: 3500000,
    generatedAt: minutesAgo(58),
  },
  {
    id: 'mock-story-11',
    headline: 'Arctic Sea Ice Hits Lowest Winter Maximum Ever Recorded',
    summary:
      'NOAA confirmed that Arctic sea ice reached its lowest winter maximum extent in the satellite record, falling below 14 million square kilometers for the first time. Scientists warn this accelerates a feedback loop of warming.',
    representativeTweets: [
      {
        id: 'mock-tweet-11a',
        text: 'Arctic winter sea ice maximum just set a grim new record — lowest in 45 years of satellite measurements. The trend line is terrifying. We are running out of time.',
        authorUsername: 'KHayhoe',
        authorDisplayName: 'Katharine Hayhoe',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(150),
        likeCount: 6200,
        retweetCount: 4100,
        replyCount: 890,
      },
      {
        id: 'mock-tweet-11b',
        text: 'NOAA data confirms: Arctic winter ice maximum fell below 14M km² for the first time. This was supposed to happen in the 2030s based on older models. We\'re ahead of schedule — in the worst way.',
        authorUsername: 'ABORSA_NSIDC',
        authorDisplayName: 'NSIDC',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(145),
        likeCount: 4800,
        retweetCount: 3200,
        replyCount: 620,
      },
    ],
    isHeadline: false,
    category: 'breaking',
    score: 0.55,
    totalEngagement: 19810,
    velocity: 830,
    uniqueAuthors: 2,
    clusterSize: 18,
    totalImpressions: 1200000,
    generatedAt: minutesAgo(130),
  },
  {
    id: 'mock-story-12',
    headline: 'Real Madrid Stunned by Atalanta in Champions League Quarterfinal',
    summary:
      'Atalanta pulled off a historic 3-1 upset over Real Madrid at the Santiago Bernabéu in the Champions League quarterfinals first leg. A Lookman brace and a late De Ketelaere goal silenced the home crowd.',
    representativeTweets: [
      {
        id: 'mock-tweet-12a',
        text: 'FULL TIME: Real Madrid 1-3 Atalanta. Absolute SCENES at the Bernabéu. Lookman with a brace and De Ketelaere seals it in stoppage time. This is the biggest UCL upset in years.',
        authorUsername: 'ChampionsLeague',
        authorDisplayName: 'UEFA Champions League',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(85),
        likeCount: 34500,
        retweetCount: 15200,
        replyCount: 4800,
      },
      {
        id: 'mock-tweet-12b',
        text: 'Atalanta just did THAT at the Bernabéu. Gasperini masterclass. Real Madrid completely outplayed in the second half. Football is beautiful.',
        authorUsername: 'FabrizioRomano',
        authorDisplayName: 'Fabrizio Romano',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(82),
        likeCount: 21300,
        retweetCount: 5600,
        replyCount: 2100,
      },
      {
        id: 'mock-tweet-12c',
        text: 'Lookman is having the season of his life. Two goals at the Bernabéu in a Champions League knockout round. Remember the name.',
        authorUsername: 'OptaJoe',
        authorDisplayName: 'OptaJoe',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(80),
        likeCount: 11800,
        retweetCount: 3200,
        replyCount: 980,
      },
    ],
    isHeadline: false,
    category: 'culture',
    score: 0.66,
    totalEngagement: 99480,
    velocity: 3610,
    uniqueAuthors: 3,
    clusterSize: 42,
    totalImpressions: 9800000,
    generatedAt: minutesAgo(75),
  },
  {
    id: 'mock-story-13',
    headline: 'Netflix Acquires Major Gaming Studio for $4.8B',
    summary:
      'Netflix announced the acquisition of FromSoftware parent company Kadokawa for $4.8 billion, gaining access to the Elden Ring and Dark Souls franchises. The deal signals Netflix\'s aggressive push into premium gaming.',
    representativeTweets: [
      {
        id: 'mock-tweet-13a',
        text: 'Netflix buying Kadokawa (owner of FromSoftware) for $4.8B is one of the wildest gaming acquisitions ever. Elden Ring, Dark Souls, and Armored Core — all under the Netflix umbrella now.',
        authorUsername: 'jaborsa_schreier',
        authorDisplayName: 'Jason Schreier',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(110),
        likeCount: 16400,
        retweetCount: 7200,
        replyCount: 3400,
      },
      {
        id: 'mock-tweet-13b',
        text: 'Netflix gaming went from mobile puzzlers to owning FromSoftware in 3 years. Say what you want about their strategy — this is a statement move. Miyazaki stays as director per the deal.',
        authorUsername: 'GenePark',
        authorDisplayName: 'Gene Park',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(105),
        likeCount: 8900,
        retweetCount: 2400,
        replyCount: 1100,
      },
    ],
    isHeadline: false,
    category: 'culture',
    score: 0.62,
    totalEngagement: 39400,
    velocity: 1890,
    uniqueAuthors: 2,
    clusterSize: 26,
    totalImpressions: 2200000,
    generatedAt: minutesAgo(95),
  },
  {
    id: 'mock-story-14',
    headline: 'CRISPR Gene Therapy Shows 94% Remission in Leukemia Trial',
    summary:
      'A Phase 3 clinical trial using CRISPR-edited CAR-T cells achieved 94% complete remission in patients with treatment-resistant acute lymphoblastic leukemia. The FDA is expected to fast-track approval.',
    representativeTweets: [
      {
        id: 'mock-tweet-14a',
        text: 'CRISPR CAR-T Phase 3 results are in: 94% complete remission in treatment-resistant ALL. This is one of the most significant oncology results in a decade. FDA fast-track likely.',
        authorUsername: 'EricTopol',
        authorDisplayName: 'Eric Topol',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(180),
        likeCount: 12800,
        retweetCount: 6400,
        replyCount: 1400,
      },
      {
        id: 'mock-tweet-14b',
        text: 'As a hematologist, I can\'t overstate what 94% CR in refractory ALL means. These are patients who had exhausted all options. CRISPR is delivering on its promise.',
        authorUsername: 'VPrasadMDMPH',
        authorDisplayName: 'Vinay Prasad MD',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(170),
        likeCount: 5400,
        retweetCount: 2100,
        replyCount: 580,
      },
      {
        id: 'mock-tweet-14c',
        text: 'Vertex and CRISPR Therapeutics shares both up 15%+ on the ALL trial data. The gene editing sector is finally seeing blockbuster clinical validation.',
        authorUsername: 'BiotechWatch',
        authorDisplayName: 'Biotech Watch',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(165),
        likeCount: 3900,
        retweetCount: 1200,
        replyCount: 340,
      },
    ],
    isHeadline: false,
    category: 'technology',
    score: 0.68,
    totalEngagement: 34120,
    velocity: 1260,
    uniqueAuthors: 3,
    clusterSize: 22,
    totalImpressions: 1800000,
    generatedAt: minutesAgo(155),
  },
  {
    id: 'mock-story-15',
    headline: 'Massive Ransomware Attack Cripples Hospital Systems Across Midwest',
    summary:
      'A coordinated ransomware attack attributed to the LockBit 4.0 group has knocked out electronic health records at 34 hospitals across five Midwest states. The FBI is leading the investigation as hospitals revert to paper records.',
    representativeTweets: [
      {
        id: 'mock-tweet-15a',
        text: 'BREAKING: 34 hospitals across IL, OH, IN, MI, and WI report simultaneous ransomware attack. EHR systems down, surgeries being rescheduled. FBI confirms LockBit 4.0 involvement.',
        authorUsername: 'BrianKrebs',
        authorDisplayName: 'Brian Krebs',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(95),
        likeCount: 8900,
        retweetCount: 6700,
        replyCount: 1800,
      },
      {
        id: 'mock-tweet-15b',
        text: 'The Midwest hospital ransomware attack is the largest healthcare cyber incident since Change Healthcare. Patient care is being diverted. This is a national security issue.',
        authorUsername: 'CISAgov',
        authorDisplayName: 'CISA',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(88),
        likeCount: 5200,
        retweetCount: 3900,
        replyCount: 920,
      },
    ],
    isHeadline: false,
    category: 'breaking',
    score: 0.64,
    totalEngagement: 27420,
    velocity: 5240,
    uniqueAuthors: 2,
    clusterSize: 25,
    totalImpressions: 2500000,
    generatedAt: minutesAgo(80),
  },
  {
    id: 'mock-story-16',
    headline: 'Waymo Autonomous Taxis Expand to 10 New US Cities',
    summary:
      'Waymo announced it will launch its fully autonomous ride-hailing service in 10 additional US cities by year-end, including Miami, Seattle, and Denver. The expansion triples its operational footprint.',
    representativeTweets: [
      {
        id: 'mock-tweet-16a',
        text: 'Waymo just announced expansion to Miami, Seattle, Denver, Nashville, Austin, DC, Boston, Atlanta, Portland, and Minneapolis. 10 cities at once. The autonomous taxi era is really here.',
        authorUsername: 'TechCrunch',
        authorDisplayName: 'TechCrunch',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(200),
        likeCount: 6100,
        retweetCount: 2800,
        replyCount: 940,
      },
      {
        id: 'mock-tweet-16b',
        text: 'Having used Waymo daily in SF for 8 months, I can confirm — it\'s better than human rideshare. Excited to see it expand. The safety data backs it up: 85% fewer crashes.',
        authorUsername: 'kimaborsa_mai',
        authorDisplayName: 'Kimberly Mai',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(190),
        likeCount: 3400,
        retweetCount: 890,
        replyCount: 310,
      },
    ],
    isHeadline: false,
    category: 'technology',
    score: 0.52,
    totalEngagement: 14440,
    velocity: 780,
    uniqueAuthors: 2,
    clusterSize: 15,
    totalImpressions: 900000,
    generatedAt: minutesAgo(185),
  },
  {
    id: 'mock-story-17',
    headline: 'IBM Demonstrates Practical Quantum Advantage in Drug Discovery',
    summary:
      'IBM Research published results showing its 1,121-qubit Condor processor solved a molecular simulation problem relevant to drug design faster than any classical supercomputer. The result is the first commercially meaningful quantum advantage.',
    representativeTweets: [
      {
        id: 'mock-tweet-17a',
        text: 'IBM just demonstrated real quantum advantage — not on a toy problem, but on molecular simulations for actual drug candidates. Condor processor solved it in 4 hours vs. estimated 47 days on Summit.',
        authorUsername: 'IBMResearch',
        authorDisplayName: 'IBM Research',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(280),
        likeCount: 4200,
        retweetCount: 2400,
        replyCount: 580,
      },
      {
        id: 'mock-tweet-17b',
        text: 'The IBM quantum advantage paper is legit. Peer reviewed in Nature. They simulated cytochrome P450 enzyme interactions — directly relevant to metabolizing 75% of known drugs. This matters.',
        authorUsername: 'ScottAaronson',
        authorDisplayName: 'Scott Aaronson',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(270),
        likeCount: 3100,
        retweetCount: 1400,
        replyCount: 420,
      },
    ],
    isHeadline: false,
    category: 'technology',
    score: 0.48,
    totalEngagement: 12100,
    velocity: 540,
    uniqueAuthors: 2,
    clusterSize: 12,
    totalImpressions: 600000,
    generatedAt: minutesAgo(260),
  },
  {
    id: 'mock-story-18',
    headline: 'James Webb Telescope Detects Strong Biosignature on Nearby Exoplanet',
    summary:
      'NASA announced that the James Webb Space Telescope detected dimethyl sulfide and phosphine in the atmosphere of K2-18 b, a potentially habitable exoplanet 120 light-years away. Both gases are considered strong biosignatures on Earth.',
    representativeTweets: [
      {
        id: 'mock-tweet-18a',
        text: 'NASA JWST update: Dimethyl sulfide AND phosphine detected in K2-18 b\'s atmosphere. On Earth, these are produced almost exclusively by biological processes. This is the strongest biosignature ever found on an exoplanet.',
        authorUsername: 'NASAWebb',
        authorDisplayName: 'NASA Webb Telescope',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(320),
        likeCount: 28700,
        retweetCount: 18400,
        replyCount: 5200,
      },
      {
        id: 'mock-tweet-18b',
        text: 'I want to be careful about hype, but the K2-18 b data is extraordinary. Two independent biosignatures at high confidence levels. This demands follow-up. If confirmed, it changes everything.',
        authorUsername: 'naborsa_tyson',
        authorDisplayName: 'Neil deGrasse Tyson',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(310),
        likeCount: 15200,
        retweetCount: 6800,
        replyCount: 2400,
      },
    ],
    isHeadline: false,
    category: 'technology',
    score: 0.72,
    totalEngagement: 76700,
    velocity: 1420,
    uniqueAuthors: 2,
    clusterSize: 34,
    totalImpressions: 5100000,
    generatedAt: minutesAgo(300),
  },
  {
    id: 'mock-story-19',
    headline: 'TikTok CEO Grilled in New Congressional Hearing on Youth Safety Data',
    summary:
      'TikTok CEO Shou Chew testified before the Senate Commerce Committee amid revelations from internal documents showing the company tracked addictive usage patterns in teens. Bipartisan calls for stricter regulation intensified.',
    representativeTweets: [
      {
        id: 'mock-tweet-19a',
        text: 'Shou Chew back on Capitol Hill. Internal TikTok docs show the company knew its algorithm drove compulsive use in 13-17 year olds and chose not to deploy existing mitigations. This is damning.',
        authorUsername: 'CaseyNewton',
        authorDisplayName: 'Casey Newton',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(240),
        likeCount: 11400,
        retweetCount: 5800,
        replyCount: 2600,
      },
      {
        id: 'mock-tweet-19b',
        text: '"Mr. Chew, your own engineers called this the \'addiction engine\' internally." Senator Blackburn holding up printed internal Slack messages. This hearing is brutal.',
        authorUsername: 'draborsa_taylor',
        authorDisplayName: 'Drew Harwell',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(235),
        likeCount: 8900,
        retweetCount: 4300,
        replyCount: 1800,
      },
      {
        id: 'mock-tweet-19c',
        text: 'Bipartisan agreement in the Senate is rare. But both sides just asked the FTC to open a formal investigation into TikTok\'s youth safety practices. This isn\'t going away.',
        authorUsername: 'MikeIsaac',
        authorDisplayName: 'Mike Isaac',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(228),
        likeCount: 6200,
        retweetCount: 2100,
        replyCount: 780,
      },
    ],
    isHeadline: false,
    category: 'politics',
    score: 0.60,
    totalEngagement: 43880,
    velocity: 1650,
    uniqueAuthors: 3,
    clusterSize: 30,
    totalImpressions: 4500000,
    generatedAt: minutesAgo(220),
  },
  {
    id: 'mock-story-20',
    headline: 'Federal Reserve Signals Two Rate Cuts Coming in Second Half of 2026',
    summary:
      'Fed Chair Jerome Powell indicated in a press conference that the FOMC sees two 25-basis-point rate cuts as appropriate before year-end, citing cooling inflation data and a softening labor market. Bond markets rallied immediately.',
    representativeTweets: [
      {
        id: 'mock-tweet-20a',
        text: 'Powell just explicitly guided to two rate cuts in H2 2026. "The data now supports a gradual normalization of policy." 10-year yield dropping fast. Mortgage rates could finally come down.',
        authorUsername: 'NickTimiraos',
        authorDisplayName: 'Nick Timiraos',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(420),
        likeCount: 9800,
        retweetCount: 4600,
        replyCount: 1900,
      },
      {
        id: 'mock-tweet-20b',
        text: 'S&P 500 up 1.2% in the 30 minutes since Powell\'s rate cut signal. Russell 2000 up 2.4%. Small caps love rate cuts. The market rotation could be real this time.',
        authorUsername: 'LizAnnSonders',
        authorDisplayName: 'Liz Ann Sonders',
        authorProfileImageUrl: 'https://pbs.twimg.com/profile_images/placeholder/avatar_400x400.jpg',
        createdAt: minutesAgo(415),
        likeCount: 5400,
        retweetCount: 1800,
        replyCount: 620,
      },
    ],
    isHeadline: false,
    category: 'business',
    score: 0.45,
    totalEngagement: 24120,
    velocity: 910,
    uniqueAuthors: 2,
    clusterSize: 20,
    totalImpressions: 1500000,
    generatedAt: minutesAgo(400),
  },
];
